'use client';
import {useEffect,useReducer,useRef,useState} from 'react';
import {Coins,Sprout,Leaf,Flower2,Apple,Carrot,Pause,Play,ShoppingBag,BarChart3,Maximize,Minimize,LockKeyhole,Sparkles,Check,Coffee,RotateCw,Shirt,Fence,BookOpen,Droplets,Footprints,Archive} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Action,Category,GardenState,Plant,Outfit,MAX_LEVEL,DISPLAY_SPACES,categories,gardenReducer,gardenerActivity,getLevel,getPlant,getOutfit,growth,initialState,outfits,plants,timeLeft,unlockedAt} from '@/lib/garden';

const atlas:Record<Category,string>={Flowers:'/flowers.png',Fruits:'/fruits.png',Vegetables:'/vegetables.png'};
function Sprite({plant,className=''}:{plant:Plant;className?:string}){return <span aria-hidden="true" className={`plant-sprite ${className}`} style={{backgroundImage:`url(${atlas[plant.category]})`,backgroundPosition:`${plant.sprite%5/4*100}% ${Math.floor(plant.sprite/5)/2*100}%`}}/>;}
function GardenerSprite({outfit,pose=0,className=''}:{outfit:Outfit;pose?:number;className?:string}){return <span aria-hidden="true" className={`gardener-sprite ${className}`} style={{backgroundPosition:`${pose/3*100}% ${outfit.sprite/5*100}%`}}/>;}
function clock(ms:number){const n=Math.ceil(ms/1000);return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;}
function duration(p:Plant){return p.minutes.length>1?`${p.minutes[0]}m · ${p.minutes[1]}m break · ${p.minutes[2]}m`:`${p.minutes[0]} min focus`;}
const displayPositions=[{left:'29%',top:'24%'},{left:'41%',top:'23%'},{left:'53%',top:'24%'},{left:'65%',top:'27%'},{left:'65%',top:'45%'},{left:'63%',top:'63%'},{left:'49%',top:'66%'},{left:'19%',top:'47%'}];
type Context={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};

export default function Garden(){
 const [state,dispatch]=useReducer(gardenReducer,undefined,initialState);
 const [now,setNow]=useState(0),[shopOpen,setShopOpen]=useState(false),[statsOpen,setStatsOpen]=useState(false),[wardrobeOpen,setWardrobeOpen]=useState(false),[farmOpen,setFarmOpen]=useState(false),[displaySlot,setDisplaySlot]=useState(0),[category,setCategory]=useState<Category>('Vegetables'),[celebration,setCelebration]=useState<GardenState['levelEvent']>(null),[fullScreen,setFullScreen]=useState(false);
 const ref=useRef(state);ref.current=state;
 const s=state.session,selected=getPlant(state.selectedSeed),active=s?getPlant(s.plantId):selected,level=getLevel(state.xp),percent=s?growth(s,now||Date.now()):0,remaining=s?timeLeft(s,now||Date.now()):selected.minutes[0]*(state.quick?1000:60000),available=unlockedAt(level),nextSeed=plants.find(p=>p.unlockLevel===level+1),outfit=getOutfit(state.outfit);
 const canPlant=state.inventory[selected.id]>0&&selected.unlockLevel<=level;
 const quickSeeds=[...new Set([selected.id,...available.filter(p=>state.inventory[p.id]>0).map(p=>p.id),'carrot'])].slice(0,3).map(getPlant);
 const activity=gardenerActivity(s,now||Date.now()),walking=activity==='roam'||activity==='walk-to'||activity==='walk-back';
 const pose=activity==='study'?2:activity==='water'?3:activity==='walk-back'?1:activity==='roam'&&Math.floor((now||0)/9000)%2===1?1:0;
 const activityLabel=activity==='study'?'Studying with you':activity==='water'?'Watering your plant':activity==='walk-to'?'Going to water':activity==='walk-back'?'Back to the book':s?.phase===1?'Taking a garden break':'Exploring the garden';
 useEffect(()=>{const id=setInterval(()=>{const t=Date.now();setNow(t);dispatch({type:'tick',now:t});},100);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!state.levelEvent)return;setCelebration(state.levelEvent);const id=setTimeout(()=>setCelebration(null),5000);return()=>clearTimeout(id);},[state.levelEvent]);
 useEffect(()=>{if(s?.status==='ready')toast.success('Ready to harvest',{description:`Harvest for ${active.coins} coins, or keep for display. Both earn ${active.xp} XP.`});else if(s?.status==='awaiting')toast(s.phase===0?'Focus session finished. Take a little break.':'Break finished. Ready for your next focus session?');},[s?.status,s?.phase,active.name,active.coins,active.xp]);
 useEffect(()=>{const update=()=>setFullScreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update);},[]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:Context}).modelContext??(navigator as Navigator&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const life=new AbortController();
  const read=(st:GardenState)=>({coins:st.coins,xp:st.xp,level:getLevel(st.xp),unlockedSeeds:unlockedAt(getLevel(st.xp)).map(p=>p.id),inventory:st.inventory,quickPlay:st.quick,selectedSeed:st.selectedSeed,session:st.session,keptPlants:st.keptPlants,displaySlots:st.displaySlots,outfit:st.outfit,ownedOutfits:st.ownedOutfits});
  async function act(a:Action){const before=ref.current;if(gardenReducer(before,a)===before)throw new Error('Action unavailable. Check your level, coins, seeds, or growing status.');dispatch(a);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return read(ref.current);}
  const list=[
   {name:'read_garden',title:'Read garden',description:'Read garden level, coins, XP, seeds, display collection, outfit, and current growth.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>read(ref.current)},
   {name:'buy_seed',title:'Buy seed',description:'Spend coins on one unlocked seed and select it.',inputSchema:{type:'object',properties:{plantId:{type:'string',enum:plants.map(p=>p.id)}},required:['plantId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {plantId?:unknown})?.plantId;if(typeof id!=='string'||!plants.some(p=>p.id===id))throw new Error('Choose a valid plantId.');return act({type:'buy',id});}},
   {name:'plant_selected_seed',title:'Plant seed',description:'Consume the selected seed in the main plot and begin growing during a focus session.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>act({type:'plant',now:Date.now()})},
   {name:'harvest_ready_plant',title:'Harvest plant',description:'Harvest a ready plant once for coins and XP.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>act({type:'harvest'})},
   {name:'keep_ready_plant',title:'Keep plant for display',description:'Keep a ready plant in the display collection. Earn XP and no coins. Place in the first empty display space when available.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>act({type:'keep'})},
  ];for(const t of list){try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();
 },[]);
 function perform(a:Action){if(gardenReducer(state,a)===state)return;dispatch(a);if(a.type==='buy')toast.success(`${getPlant(a.id).name} seed added to your bag`);if(a.type==='harvest')toast.success('Harvest collected',{description:`+${active.coins} coins · +${active.xp} XP`});if(a.type==='keep'){toast.success('Plant kept for display',{description:`+${active.xp} XP · 0 coins`});if(!state.displaySlots.includes(null))setFarmOpen(true);}if(a.type==='buyOutfit')toast.success(`${getOutfit(a.id).name} bought and equipped`);}
 function primary(){const t=Date.now();setNow(t);if(!s)perform({type:'plant',now:t});else if(s.status==='ready')perform({type:'harvest'});else if(s.status==='awaiting')perform({type:'next',now:t});else perform({type:s.status==='paused'?'resume':'pause',now:t});}
 async function enterFullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return;}await document.documentElement.requestFullscreen();const orientation=screen.orientation as ScreenOrientation&{lock?:(value:string)=>Promise<void>};await orientation.lock?.('landscape').catch(()=>{});}catch{toast('Full screen is unavailable in this browser.');}}
 const heading=!s?'Plant a seed':s.status==='ready'?'Ready to harvest':s.phase===1?'Taking a break':'Growing';
 const actionLabel=!s?'Plant seed':s.status==='ready'?'Harvest':s.status==='awaiting'?(s.phase===0?'Start break':'Start focus session'):s.status==='paused'?'Resume growing':'Pause growing';
 return <main className="app-stage"><Toaster position="top-center" theme="light"/>
  <div className="rotate-prompt"><RotateCw size={58}/><h1>A little room to grow</h1><p>Turn your device to landscape to enter your garden.</p><span>FOCUS GARDEN</span></div>
  <section className="game-screen" aria-label="Focus Garden landscape game">
   <div className="farm-world" aria-hidden="true"/>
   <header className="game-header">
    <div className="wood-panel game-brand"><Sprout size={28}/><div><h1>Focus Garden</h1><span><LockKeyhole size={12}/>Your private garden</span></div></div>
    <div className="garden-hud"><div className="wood-panel level-panel"><span className="level-badge">{level}<small>LV</small></span><div><strong>{level===MAX_LEVEL?'Master gardener':'Growing gardener'}</strong><div className="xp-label"><span>XP</span><span>{level===MAX_LEVEL?'MAX':`${state.xp%100} / 100`}</span></div><Progress aria-label="XP to next garden level" value={level===MAX_LEVEL?100:state.xp%100}/></div></div><div className="wood-panel coin-panel"><Coins/><strong data-testid="coins">{state.coins}</strong><span>Coins</span></div></div>
   </header>

   <div className="display-farm" aria-label="Display farm">{state.displaySlots.map((id,i)=>{const kept=state.keptPlants.find(p=>p.id===id),plant=kept?getPlant(kept.plantId):null;return <button key={i} className={`display-space ${plant?'occupied':''}`} style={displayPositions[i]} aria-label={`Display space ${i+1}${plant?`, ${plant.name}`:', empty'}`} onClick={()=>{setDisplaySlot(i);setFarmOpen(true);}}>{plant?<Sprite plant={plant}/>:<Flower2 className="empty-display-icon" size={23}/>}<span className="display-number">{i+1}</span></button>;})}</div>
   <div role="group" className={`garden-bed main-bed selected ${s?'planted':''} ${s?.status==='ready'?'ready':''}`} aria-label={s?`${active.name} in main plot, ${s.status==='ready'?'ready to harvest':s.phase===1?'resting':s.status==='paused'?'paused':'growing'}`:'Main growing plot, empty'}>
    <span className="bed-cells" aria-hidden="true">{Array.from({length:9},(_,n)=><span key={n}/>)}</span>
    {s?<div className={`crop ${s.status==='paused'?'paused':''} ${s.status==='ready'?'ripe':''}`} style={{'--growth':percent} as React.CSSProperties}>{percent<.3?<span className="sprout-sprite"/>:<Sprite plant={active}/>}</div>:<Sprout className="empty-sprout" size={40}/>}
    <span className={`bed-label ${s?.status==='ready'?'ready-label':''}`}>{s?.status==='ready'?<><Sparkles size={13}/>Ready to harvest</>:s?s.phase===1?'Resting':s.status==='paused'?'Paused':`${Math.floor(percent*100)}% grown`:'Main growing plot'}</span>
    {s?.status==='running'&&s.phase!==1&&<span className="growth-glints" aria-hidden="true"><i/><i/><i/></span>}
   </div>
   {s&&s.status!=='ready'&&<span className={`study-table ${activity==='study'?'at-desk':''}`} aria-hidden="true"/>}
   <div className={`gardener ${activity} ${walking?'walking':''} ${celebration?'level-dance':''}`} aria-label={`Gardener: ${activityLabel}`}><GardenerSprite outfit={outfit} pose={pose}/><span className="gardener-status">{activity==='study'?<BookOpen size={13}/>:activity==='water'?<Droplets size={13}/>:<Footprints size={13}/>}<span>{activityLabel}</span></span></div>

   <div className="wood-panel garden-dialogue" aria-live="polite"><Sprout size={18}/><p>{state.message}</p></div>
   <aside className="wood-panel growing-panel" aria-label="Growing">
    <div className="growing-heading"><span>{s?.phase===1?<Coffee size={17}/>:s?.status==='ready'?<Sparkles size={17}/>:<Leaf size={17}/>} {heading}</span><span className="play-badge">{state.quick?'Quick play':'Focus session'}</span></div>
    <div className="growing-details"><Sprite plant={active}/><div><h2>{active.name}</h2><span className={`rarity rarity-${active.rarity.toLowerCase()}`}>{active.rarity}</span><p>{duration(active)}</p></div><strong className="growth-clock" role="timer" aria-label="Growing time remaining">{s?.status==='ready'?<Check size={31}/>:clock(remaining)}</strong></div>
    {active.minutes.length>1&&<div className="phase-track">{active.minutes.map((n,i)=><span key={i} className={s?.phase===i?'current':''}>{i===1?'Break':'Focus'} {n}m</span>)}</div>}
    <Progress className="plant-progress" aria-label="Plant growth" value={percent*100}/>
    <div className="growing-rewards"><span><Coins size={14}/>+{active.coins} coins</span><span><Sparkles size={14}/>+{active.xp} XP</span></div>
    <button className="plant-button" disabled={!s&&!canPlant} onClick={primary}>{!s?<Sprout size={18}/>:s.status==='ready'?<ShoppingBag size={18}/>:s.status==='running'?<Pause size={18}/>:<Play size={18}/>} {actionLabel}{s?.status==='ready'&&<small>+{active.coins} coins</small>}</button>
    {s?.status==='ready'&&<button className="keep-button" onClick={()=>perform({type:'keep'})}><Flower2 size={17}/>Keep for display <small>0 coins</small></button>}
    <p className="growing-note">{!s?selected.unlockLevel>level?`Unlocks at level ${selected.unlockLevel}`:state.inventory[selected.id]===0?'Buy this seed in the seed shed':`${state.inventory[selected.id]} ${selected.name} seeds in your bag`:s.status==='ready'?`Either choice earns ${active.xp} XP. Only harvest gives coins.`:s.status==='awaiting'?(s.phase===0?'Your first focus session is complete.':'Your plant needs one more focus session.'):'One plant, one focus session at a time.'}</p>
   </aside>

   <nav className="wood-panel game-toolbar" aria-label="Garden controls">
    <div className="seed-shortcuts">{quickSeeds.map(p=><button key={p.id} className={`seed-slot ${selected.id===p.id?'chosen':''}`} aria-label={`Select ${p.name} seed, ${state.inventory[p.id]} owned`} aria-pressed={selected.id===p.id} onClick={()=>dispatch({type:'selectSeed',id:p.id})}><Sprite plant={p}/><span>{state.inventory[p.id]}</span></button>)}</div>
    <span className="toolbar-divider"/>
    <button className="tool-button" aria-label="Seed shed" title="Seed shed" onClick={()=>setShopOpen(true)}><ShoppingBag size={22}/><span>Seed shed</span></button>
    <button className="tool-button" aria-label="Wardrobe" title="Wardrobe" onClick={()=>setWardrobeOpen(true)}><Shirt size={22}/><span>Wardrobe</span></button>
    <button className="tool-button" aria-label="Display farm" title="Display farm" onClick={()=>setFarmOpen(true)}><Fence size={22}/><span>Display farm</span></button>
    <button className="tool-button" aria-label="Garden stats" title="Garden stats" onClick={()=>setStatsOpen(true)}><BarChart3 size={22}/><span>Garden stats</span></button>
    <button className="tool-button fullscreen-button" onClick={enterFullscreen} aria-label={fullScreen?'Leave full screen':'Enter full screen'}>{fullScreen?<Minimize size={22}/>:<Maximize size={22}/>}</button>
    <div className="quick-control"><label htmlFor="quick-play">Quick play</label><Switch id="quick-play" checked={state.quick} disabled={!!s} onCheckedChange={quick=>dispatch({type:'mode',quick})}/></div>
   </nav>

   {celebration&&<div className="level-celebration" role="status" aria-live="polite" key={celebration.key}><div className="confetti" aria-hidden="true">{Array.from({length:14},(_,i)=><i key={i} style={{'--i':i,'--x':`${Math.cos(i*2.4)*170}px`,'--y':`${Math.sin(i*2.4)*105}px`,'--turn':`${i*77}deg`} as React.CSSProperties}/>)}</div><div className="wood-panel level-up-card"><Sparkles className="level-sparkle"/><span>LEVEL UP!</span><h2>Level {celebration.to}</h2><p>{celebration.seeds.length===1?'One new seed unlocked':`${celebration.seeds.length} levels · ${celebration.seeds.length} new seeds`}</p><div>{celebration.seeds.map(id=><Sprite key={id} plant={getPlant(id)}/>)}</div><small>{celebration.seeds.map(id=>getPlant(id).name).join(' · ')}</small></div></div>}
  </section>

  <Dialog open={shopOpen} onOpenChange={setShopOpen}><DialogContent className="game-modal seed-modal"><div className="modal-heading"><div><DialogTitle>Seed shed</DialogTitle><DialogDescription>One seed per level: vegetable, fruit, flower. 45 levels to grow.</DialogDescription></div><span className="modal-coins"><Coins size={19}/>{state.coins} Coins</span></div>
   <Tabs value={category} onValueChange={value=>setCategory(value as Category)}><TabsList className="category-tabs">{categories.map(c=><TabsTrigger key={c} value={c}>{c==='Flowers'?<Flower2/>:c==='Fruits'?<Apple/>:<Carrot/>}{c}</TabsTrigger>)}</TabsList>{categories.map(c=><TabsContent key={c} value={c}><div className="catalog-grid">{plants.filter(p=>p.category===c).map(p=>{const locked=p.unlockLevel>level;return <article key={p.id} className={`catalog-seed ${locked?'locked':''} ${selected.id===p.id?'picked':''}`}><button className="catalog-choice" aria-label={`Choose ${p.name}, ${locked?`unlocks at level ${p.unlockLevel}`:`${p.rarity} seed`}`} onClick={()=>dispatch({type:'selectSeed',id:p.id})}><Sprite plant={p}/><h3>{p.name}</h3><span className={`rarity rarity-${p.rarity.toLowerCase()}`}>{p.rarity}</span><span className="seed-duration">{duration(p)}</span><span className="seed-reward">{p.coins} coins · {p.xp} XP</span><span className="owned-count">×{state.inventory[p.id]}</span></button><button className="catalog-buy" disabled={locked||state.coins<p.cost} aria-label={locked?`${p.name} locked until level ${p.unlockLevel}`:`Buy ${p.name} seed for ${p.cost} coins`} onClick={()=>perform({type:'buy',id:p.id})}>{locked?<><LockKeyhole size={13}/>Level {p.unlockLevel}</>:<>Buy <Coins size={13}/>{p.cost}</>}</button></article>;})}</div></TabsContent>)}</Tabs>
   <div className="catalog-footer"><span>Level {level} · {available.length} / 45 seeds unlocked</span><button disabled={!canPlant||!!s} onClick={()=>setShopOpen(false)}>Use {selected.name} seed</button></div>
  </DialogContent></Dialog>

  <Dialog open={wardrobeOpen} onOpenChange={setWardrobeOpen}><DialogContent className="game-modal wardrobe-modal"><div className="modal-heading"><div><DialogTitle>Garden wardrobe</DialogTitle><DialogDescription>Unlock an outfit, buy it with coins, then wear it any time.</DialogDescription></div><span className="modal-coins"><Coins size={19}/>{state.coins} Coins</span></div><div className="outfit-grid">{outfits.map(o=>{const owned=state.ownedOutfits.includes(o.id),equipped=state.outfit===o.id,locked=level<o.level;return <article key={o.id} className={`outfit-card ${equipped?'equipped':''}`}><GardenerSprite outfit={o}/><h3>{o.name}</h3><p>{o.description}</p><button className="catalog-buy" disabled={equipped||locked||(!owned&&state.coins<o.cost)} aria-label={equipped?`${o.name} equipped`:locked?`${o.name} locked until level ${o.level}`:owned?`Equip ${o.name}`:`Buy ${o.name} outfit for ${o.cost} coins`} onClick={()=>perform({type:owned?'equipOutfit':'buyOutfit',id:o.id})}>{equipped?<><Check size={15}/>Equipped</>:locked?<><LockKeyhole size={14}/>Level {o.level}</>:owned?'Equip':<>Buy <Coins size={14}/>{o.cost}</>}</button></article>;})}</div></DialogContent></Dialog>

  <Dialog open={farmOpen} onOpenChange={setFarmOpen}><DialogContent className="game-modal farm-modal"><DialogTitle>Display farm</DialogTitle><DialogDescription>Keep a finished plant instead of harvesting it. Display plants earn no coins and stay in your collection.</DialogDescription><div className="display-picker" aria-label="Choose a display space">{state.displaySlots.map((id,i)=>{const p=state.keptPlants.find(p=>p.id===id);return <button key={i} className={displaySlot===i?'chosen':''} aria-label={`Choose display space ${i+1}`} aria-pressed={displaySlot===i} onClick={()=>setDisplaySlot(i)}>{p?<Sprite plant={getPlant(p.plantId)}/>:<Flower2 size={25}/>}<span>{i+1}</span></button>;})}</div><div className="collection-heading"><h3>Your plants · {state.keptPlants.length}</h3><button disabled={!state.displaySlots[displaySlot]} onClick={()=>perform({type:'clearDisplay',slot:displaySlot})}><Archive size={15}/>Store plant from space {displaySlot+1}</button></div>
   {state.keptPlants.length?<div className="collection-grid">{state.keptPlants.map(p=>{const plant=getPlant(p.plantId),inSlot=state.displaySlots.indexOf(p.id);return <article key={p.id}><Sprite plant={plant}/><h3>{plant.name}</h3><span>{inSlot===-1?'In collection':`In display space ${inSlot+1}`}</span><button className="catalog-buy" disabled={state.displaySlots[displaySlot]===p.id} aria-label={`Display ${plant.name} in space ${displaySlot+1}`} onClick={()=>perform({type:'placeDisplay',id:p.id,slot:displaySlot})}>{state.displaySlots[displaySlot]===p.id?'Displayed':`Place in ${displaySlot+1}`}</button></article>;})}</div>:<div className="collection-empty"><Flower2 size={40}/><h3>Your display farm is waiting</h3><p>Finish growing a plant, then choose “Keep for display”.</p><p>You’ll earn focus XP and keep the plant. Harvest when you want coins.</p></div>}
   <p className="prototype-note">Moving or storing a plant never earns extra XP or coins. Replaced plants return to your collection.</p>
  </DialogContent></Dialog>

  <Dialog open={statsOpen} onOpenChange={setStatsOpen}><DialogContent className="game-modal stats-modal"><DialogTitle>Garden stats</DialogTitle><DialogDescription>One new seed each level: vegetable → fruit → flower.</DialogDescription><div className="stats-grid"><div><span>Garden level</span><strong>{level} / {MAX_LEVEL}</strong></div><div><span>Harvests</span><strong>{state.harvests}</strong></div><div><span>Plants kept</span><strong>{state.keptPlants.length}</strong></div><div><span>Total XP</span><strong>{state.xp}</strong></div><div><span>Focus time</span><strong>{Math.floor(state.focusedSeconds/60)}m {state.focusedSeconds%60}s</strong></div><div><span>Seeds unlocked</span><strong>{available.length} / 45</strong></div></div>{nextSeed?<div className="next-unlocks"><h3>Next at level {level+1}</h3><p>{100-state.xp%100} XP to unlock {nextSeed.name}</p><div><div><Sprite plant={nextSeed}/><strong>{nextSeed.name}</strong><span>{nextSeed.category}</span><span className={`rarity rarity-${nextSeed.rarity.toLowerCase()}`}>{nextSeed.rarity}</span></div></div></div>:<p className="all-unlocked"><Sparkles/>All 45 seeds are yours to grow.</p>}<p className="prototype-note">Quick play: 1 focus minute takes 1 second. Progress lasts for this visit and resets on refresh.</p></DialogContent></Dialog>
 </main>;
}
